from pydantic import BaseModel
from typing import List, Optional

#you have to come up with 2 models now, demand and supply, also differentiate based on property type, there are different attributes for different property types
class Property(BaseModel):
    property_id: Optional[str] = None #will be autogenerated if not provided
    title: str
    description: Optional[str] = None
    locality: Optional[str] = None
    #city: Optional[str] = None
    #state: Optional[str] = None
    price: Optional[float] = None
    bhk: Optional[int] = None
    bathrooms: Optional[int] = None
    area_sqft: Optional[int] = None
    furnishing_status: Optional[str] = None #remove one
    furnished_or_unfurnished: Optional[bool] = None
    property_type: Optional[str] = None
    amenities: Optional[List[str]] = []
    listed_date: Optional[str] = None
    available_from: Optional[str] = None
    age_of_building: Optional[int] = None
    lift_available: Optional[bool] = None
    floor_number: Optional[int] = None
    no_of_toilets: Optional[int] = None
    balconies: Optional[int] = None
    #geo_location: Optional[dict] = None
